version: "3.9"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db

    web:
        build: Docker
        restart: on-failure
        volumes:
            - ./app:/app:rw
        ports:
            - 8005:80
        environment:
            - TZ=Europe/Paris

volumes:
    db-data: null
